core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .forms import LoginForm
from .views import index, contato, cadastro


urlpatterns = [
    path('', index, name='index'),
    path('contato/', contato, name='contato'),
    path('signup/', cadastro, name='cadastro'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login')
]

item/urls.py
from django.urls import path

from .views import detail, novoitem, delete, edita, items

app_name = 'item'

urlpatterns = [
    path('<int:id>/', detail, name='detalhes'),
    path('delete/<int:id>',delete, name='delete'),
    path('edita/<int:id>', edita, name='edita'),
    path('novo_item/', novoitem, name='novo_item'),
    path('', items, name='items')
]

starker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    nome = models.CharField(max_length=255)

    class Meta:
        ordering = ('nome',)
        verbose_name_plural = "Categories"
        
    def __str__(self):
        return self.nome
    
class Item(models.Model):
    categoria = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    nome = models.CharField(max_length=255)
    descricao = models.TextField(blank=True, null=True)
    preco = models.FloatField()
    imagem = models.ImageField(upload_to='images', blank=True, null=True)
    a_venda = models.BooleanField(default=False)
    criado_por = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    criado_em = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nome

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class novoItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('categoria', 'nome', 'descricao', 'preco', 'imagem')
        widgets = {
            'categoria': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'nome': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'descricao': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'preco': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'imagem': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }
class EditaItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('nome', 'descricao', 'preco', 'imagem', 'a_venda')
        widgets = {
            'nome': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'descricao': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'preco': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'imagem': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Item, Category
from .forms import novoItemForm, EditaItemForm

def items(request):
    query = request.GET.get('query', '')
    categoria_id = request.GET.get('categoria', 0)
    categorias = Category.objects.all()
    items = Item.objects.filter(a_venda=False)
    
    if categoria_id:
        items = items.filter(categoria_id=categoria_id)
    
    if query:
        items = items.filter(Q(nome__icontains=query) | Q(descricao__icontains=query))
    context = {
        'items': items,
        'query': query,
        'categorias': categorias,
        'categoria_id': int(categoria_id)
    }
    return render(request, 'item/items.html', context)

def detail(request, id):
    print(id)
    item = get_object_or_404(Item, id=id)
    itens_relacionados = Item.objects.filter(categoria=item.categoria, a_venda=False).exclude(id=id)[0:3]
    context = {
        "item":item,
        'itens_relacionados': itens_relacionados
    }
    return render(request, 'item/detalhe.html', context)

@login_required
def novoitem(request):
    if request.method == 'POST':
        form = novoItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.criado_por = request.user
            item.save()

            return redirect('item:detalhes', id=item.id)
    else:     
        form = novoItemForm()
        
    context = {
        'form': form,
        'title': 'novo item'
    }
    return render(request, 'item/form.html', context)

@login_required
def delete(request, id):
    item = get_object_or_404(Item, id=id, criado_por=request.user)
    item.delete()
    return redirect('dashboard:index')

@login_required
def edita(request, id):
    item = get_object_or_404(Item, id=id, criado_por=request.user)
    if request.method == 'POST':
        form = EditaItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()

            return redirect('item:detalhes', id=item.id)
    else:     
        form = EditaItemForm(instance=item)
        
    context = {
        'form': form,
        'title': 'edita item'
    }
    return render(request, 'item/form.html', context)

item/templates/item/detalhe.html
{%extends 'base.html'%}

{%block title%}{{item.nome}}{%endblock%}

{%block content%}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.imagem.url}}" class="rounded-xl" style="max-width: 60%;">
    </div>


    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{item.nome}}</h1>
        <p class="text-gray-500"><strong>Preço: </strong>{{item.preco}}</p>
        <p class="text-gray-500"><strong>Vendedor: </strong>{{item.criado_por}}</p>
        {%if item.descricao%}
            <p class="text-gray-700"><strong class="text-gray-500">Descrição: </strong>{{item.descricao}}</p>
        {%endif%}

        {%if request.user == item.criado_por%}
        <div class="mt-6 p-6 bg-white rounded-xl">
            <p>Esse é o seu item</p>

            <a href="/item/edita/{{item.id}}" class="inline-block mt-6 px-6 py-3 text-lg text-white font-semibold bg-teal-500 rounded-xl">Editar</a>
            <a href="/item/delete/{{item.id}}" class="inline-block mt-6 px-6 py-3 text-lg text-white font-semibold bg-red-500 rounded-xl">Deletar</a>
        </div>
        {%endif%}

        <a href="/inbox/novo/{{item.id}}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contatar vendedor</a>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Itens Relacionados</h2>

    <div class="grid grid-cols-3 gap-3">
        {%for item in itens_relacionados%}
        <div>
            <a href="/item/{{item.id}}">
                <div>
                    <img src="{{item.imagem.url}}" alt="{{item.nome}}" class="rounded-t-xl" width="400" height="500">
                </div>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{item.nome}}</h2>
                    <p class="text-gray-500">Preço: {{item.preco}}</p>
                </div>
            </a>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

item/templates/item/form.html
{%extends 'base.html'%}

{%block title%}{{title}}{%endblock title%}

{%block content%}
<h1 class="mb-6 text-3xl">{{title}}</h1>

<form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    <div class="space-y-4">
        {{form.as_p}}
    </div>

    {%if form.errors or form.non_field_errors%}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {%for field in form%}
            {{field.errors}}
        {%endfor%}

        {{form.non_field_errors}}
    </div>
    {%endif%}

    
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
</form>
{%endblock content%}

item/templates/item/items.html
{%extends 'base.html'%}

{%block title %} Items {%endblock%}

{%block content%}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100 p-5 rounded-xl">
    <div class="col-span-1">
        <form method="get" action="{%url 'item:items' %}">
            <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}"
                placeholder="Encontre bike, relogio, consoles....">
            <button class="mt-5 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Buscar</button>
        </form>

        <hr class="my-6">

        <p class="font-semibold">Categorias</p>

        <ul>
            {%for categoria in categorias%}

            <li class="py-2 px-2 rounded-xl{%if categoria.id == categoria_id %} bg-gray-200 {%endif%} ">
                <a href="/item/?query={{query}}&categoria={{categoria.id}}">{{categoria.nome}}</a>
            </li>

            {%endfor%}
        </ul>

        <hr class="my-6">
        <p class="font-semibold">Limpar Filtro</p>
        <ul>
            <li><a href="/item/" class="mt-5 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Limpar</a></li>
        </ul>
    </div>

    <div class="col-span-3">
        <div class="grid grid-cols-3 gap-3">
            {%for item in items%}
            <div>
                <a href="/item/{{item.id}}">
                    <div>
                        <img src="{{item.imagem.url}}" alt="{{item.nome}}" class="rounded-t-xl" width="400"
                            height="500">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.nome}}</h2>
                        <p class="text-gray-500">Preço: {{item.preco}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>
</div>
{%endblock content%}